### PR TITLE
Add page for LiveG's 9th birthday

### PR DESCRIPTION
**Pull request by James-Livesey**
LiveG will be 9 years old on 30 November 2023, so to celebrate, we're creating a page that details LiveG's progress over the last year, and will also include one or more fun but trivial coding activities (relating to LiveG Astronaut) that visitors can enjoy.

### CODE REVIEW

**Comment by tramcrazy** [comment]
Have tested the challenge and can confirm it works.
Few small bits:
- as the code editor is a textarea tabbing for code indentation doesn't work and focus jumps to the next focusable area, but I'm aware the *Livesey 4-Space Indentation Solution* works fine
- it's ambiguous how big you need to make the cake layer width  and base width to proceed to the next steps.
Other than that it all seems good!

**Comment by James-Livesey** [comment]
Added smart indentation to Typeset Engine in this PR (needs approval): https://github.com/LiveGTech/Typeset-Engine/pull/2

Will get to work on improving clarity for the coding challenge regarding setting cake width.

**Comment by James-Livesey** [comment]
Improved the clarity by writing this message:

> Much better! How about increasing the `width`s of both layers so that we can still fit all the candles on? Try making the cake layers tiered, with the top layer having a width of at least `9`.

Hopefully this still maintains some level of difficulty (with the term 'tiered' implying that each layer must increase in width from the last). It was definitely worth adding the "width of at least `9`" part as users wouldn't know that the initial width is `8`!

**Comment by James-Livesey** [comment]
Changes approved by @tramcrazy on Discord, merging now with a view to release before 12:00 UTC tomorrow. This is so that the page shows as soon as it is 30 November in UTC+12 (furthest ahead in time).

**Pull request merged**
